# Generated by Django 4.2.2 on 2023-06-21 10:31

import _socket
import audit_fields.fields.hostname_modification_field
import audit_fields.fields.userfield
import audit_fields.models.audit_model_mixin
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('repayment_id', models.CharField(max_length=45)),
                ('branch_id', models.CharField(max_length=255)),
                ('repayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('loan_repayment_method_id', models.CharField(blank=True, max_length=45, null=True)),
                ('repayment_collected_date', models.CharField(blank=True, max_length=45, null=True)),
                ('collector_id', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_do_not_adjust_remaining_pro_rata', models.CharField(blank=True, max_length=45, null=True)),
                ('repayment_adjust_remaining_schedule', models.CharField(blank=True, max_length=45, null=True)),
                ('repayment_manual_composition', models.CharField(blank=True, max_length=45, null=True)),
                ('principal_repayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('interest_repayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fees_repayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('penalty_repayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('repayment_description', models.CharField(blank=True, max_length=45, null=True)),
                ('LoanId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='loan.loan')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_repay', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_by_repay', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
