# Generated by Django 4.2.2 on 2023-06-21 10:29

import _socket
import audit_fields.fields.hostname_modification_field
import audit_fields.fields.userfield
import audit_fields.models.audit_model_mixin
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('borrower_id', models.CharField(max_length=45)),
                ('branch_id', models.CharField(max_length=255)),
                ('borrower_country', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_fullname', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_firstname', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_lastname', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_business_name', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_unique_number', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_gender', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_title', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_mobile', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_email', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_dob', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_address', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_city', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_province', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_zipcode', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_landline', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_working_status', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_credit_score', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_description', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_access_ids', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_photo', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_id+', to='organisation.organisation')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
