# Generated by Django 4.2.2 on 2023-06-21 10:28

import _socket
import audit_fields.fields.hostname_modification_field
import audit_fields.fields.userfield
import audit_fields.models.audit_model_mixin
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrower', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('loan_id', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_product_id', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_application_id', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_disbursed_by_id', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_principal_amount', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_released_date', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_interest_method', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_interest_type', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_interest_period', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_interest', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_duration_period', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_duration_type', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_duration', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_payment_scheme_id', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_num_of_repayments', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_decimal_places', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_interest_start_date', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_fees_pro_rata', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_do_not_adjust_remaining_pro_rata', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_first_repayment_pro_rata', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_first_repayment_date', models.CharField(blank=True, max_length=45, null=True)),
                ('first_repayment_amount', models.CharField(blank=True, max_length=45, null=True)),
                ('last_repayment_amount', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_override_maturity_date', models.CharField(blank=True, max_length=45, null=True)),
                ('override_each_repayment_amount', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_interest_each_repayment_pro_rata', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_interest_schedule', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_principal_schedule', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_balloon_repayment_amount', models.CharField(blank=True, max_length=45, null=True)),
                ('automatic_payments', models.CharField(blank=True, max_length=45, null=True)),
                ('payment_posting_period', models.CharField(blank=True, max_length=45, null=True)),
                ('total_amount_due', models.CharField(blank=True, max_length=45, null=True)),
                ('balance_amount', models.CharField(blank=True, max_length=45, null=True)),
                ('due_date', models.CharField(blank=True, max_length=45, null=True)),
                ('total_paid', models.CharField(blank=True, max_length=45, null=True)),
                ('child_status_id', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_fee_schedule_3951', models.CharField(blank=True, max_length=45, null=True)),
                ('loan_fee_id_3951', models.CharField(blank=True, max_length=45, null=True)),
                ('borrower_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='borrower.borrower')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_by+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
