#import arrow
from django.db import models
#from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from organisation.models import Organisation
class loan(models.Model):
    loan_id = models.CharField(max_length=45, null=True, blank=True,)
    loan_product_id = models.CharField(max_length=45, null=True, blank=True,)
    loan_application_id = models.CharField(max_length=45, null=True, blank=True,)
    loan_disbursed_by_id = models.CharField(max_length=45, null=True, blank=True,)
    loan_principal_amount = models.CharField(max_length=45, null=True, blank=True,)
    loan_released_date = models.CharField(max_length=45, null=True, blank=True,)
    loan_interest_method = models.CharField(max_length=45, null=True, blank=True,)
    loan_interest_type = models.CharField(max_length=45, null=True, blank=True,)
    loan_interest_period = models.CharField(max_length=45, null=True, blank=True,)
    loan_interest = models.CharField(max_length=45, null=True, blank=True,)
    loan_duration_period = models.CharField(max_length=45, null=True, blank=True,)
    loan_duration = models.CharField(max_length=45, null=True, blank=True,)
    loan_payment_scheme_id = models.CharField(max_length=45, null=True, blank=True,)
    loan_num_of_repayments = models.CharField(max_length=45, null=True, blank=True,)
    loan_decimal_places = models.CharField(max_length=45, null=True, blank=True,)
    loan_interest_start_date = models.CharField(max_length=45, null=True, blank=True,)
    loan_fees_pro_rata = models.CharField(max_length=45, null=True, blank=True,)
    loan_do_not_adjust_remaining_pro_rata = models.CharField(max_length=45, null=True, blank=True,)
    loan_first_repayment_pro_rata = models.CharField(max_length=45, null=True, blank=True,)
    loan_first_repayment_date = models.CharField(max_length=45, null=True, blank=True,)
    first_repayment_amount = models.CharField(max_length=45, null=True, blank=True,)
    last_repayment_amount = models.CharField(max_length=45, null=True, blank=True,)
    loan_override_maturity_date = models.CharField(max_length=45, null=True, blank=True,)
    override_each_repayment_amount = models.CharField(max_length=45, null=True, blank=True,)
    loan_interest_each_repayment_pro_rata = models.CharField(max_length=45, null=True, blank=True,)
    loan_interest_schedule = models.CharField(max_length=45, null=True, blank=True,)
    loan_principal_schedule = models.CharField(max_length=45, null=True, blank=True,)
    loan_balloon_repayment_amount = models.CharField(max_length=45, null=True, blank=True,)
    automatic_payments = models.CharField(max_length=45, null=True, blank=True,)
    payment_posting_period = models.CharField(max_length=45, null=True, blank=True,)
    total_amount_due = models.CharField(max_length=45, null=True, blank=True,)
    balance_amount = models.CharField(max_length=45, null=True, blank=True,)
    due_date = models.CharField(max_length=45, null=True, blank=True,)
    total_paid = models.CharField(max_length=45, null=True, blank=True,)
    child_status_id = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_3951 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_3951 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_4734 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_4734 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_4727 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_4727 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_4726 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_4726 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_4725 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_4725 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_4724 = models.CharField(max_length=45, null=True, blank=True,) 
    loan_fee_id_4724 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_4611 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_4611 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_4197 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_4197 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_4196 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_4196 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_4195 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_4195 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_4194 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_4194 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_4735 = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_4735 = models.CharField(max_length=45, null=True, blank=True,)
    loan_override_sys_gen_penalty = models.CharField(max_length=45, null=True, blank=True,)
    loan_manual_penalty_amount = models.CharField(max_length=45, null=True, blank=True,)
    loan_status_id = models.CharField(max_length=45, null=True, blank=True,)
    loan_title = models.CharField(max_length=45, null=True, blank=True,)
    loan_description  = models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_7548 =models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_7548 =models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_7549 =models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_7549 =models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_7838 =models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_7838 =models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_7839 =models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_7839 =models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_schedule_7840 =models.CharField(max_length=45, null=True, blank=True,)
    loan_fee_id_7840 =models.CharField(max_length=45, null=True, blank=True,)
    borrower_id = models.CharField(max_length=45, null=True, blank=True,)
    org_id=models.ForeignKey(Organisation,on_delete=models.CASCADE, null=True, blank=True,related_name='org_id+')
    branch_id = models.CharField(max_length=255)
    borrower_country = models.CharField(max_length=45, null=True, blank=True,)
    borrower_fullname = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_firstname = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_lastname = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_business_name = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_unique_number = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_gender = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_title = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_mobile = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_email = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_dob = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_address = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_city = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_province = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_zipcode = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_landline = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_working_status = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_credit_score = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_description = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_access_ids = models.CharField(max_length=45, null=True, blank=True,) 
    borrower_photo = models.CharField(max_length=45, null=True, blank=True,)
    
    """createdby = models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True,related_name='created_by+')
    createdat = models.DateTimeField(auto_now_add=True)
    modifiedby = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True,related_name='modified_by+')
    
    modifiedat = models.DateTimeField(auto_now=True)"""
   





    def __str__(self):
        return self.loan_id

   
    
