from rest_framework import serializers

from loan.models import loan



class loanSerializer(serializers.ModelSerializer):
    
   
    class Meta:
        model = loan
        fields = (
            "id",
            "loan_id",
            "loan_product_id",
            "loan_application_id",
            "loan_disbursed_by_id",
            "loan_principal_amount",
            "loan_released_date",
            "loan_interest_method",
            "loan_interest_type",
            "loan_interest_period",
            "loan_interest",
            "loan_duration_period",
            "loan_duration",
            "loan_payment_scheme_id",
            "loan_num_of_repayments",
            "loan_decimal_places",
            "loan_interest_start_date",
            "loan_fees_pro_rata",
            "loan_do_not_adjust_remaining_pro_rata",
            "loan_first_repayment_pro_rata",
            "loan_first_repayment_date",
            "first_repayment_amount",
            "last_repayment_amount",
            "loan_override_maturity_date",
            "override_each_repayment_amount",
            "loan_interest_each_repayment_pro_rata",
            "loan_interest_schedule",
            "loan_principal_schedule",
            "loan_balloon_repayment_amount",
            "automatic_payments",
            "payment_posting_period",
            "total_amount_due",
            "balance_amount",
            "due_date",
            "total_paid",
            "child_status_id",
            "loan_fee_schedule_3951",
            "loan_fee_id_3951",
            "loan_fee_schedule_4734",
            "loan_fee_id_4734",
            "loan_fee_schedule_4727",
            "loan_fee_id_4727",
            "loan_fee_schedule_4726",
            "loan_fee_id_4726",
            "loan_fee_schedule_4725",
            "loan_fee_id_4725",
            "loan_fee_schedule_4724",
            "loan_fee_id_4724",
            "loan_fee_schedule_4611",
            "loan_fee_id_4611",
            "loan_fee_schedule_4197",
            "loan_fee_id_4197",
            "loan_fee_schedule_4196",
            "loan_fee_id_4196",
            "loan_fee_schedule_4195",
            "loan_fee_id_4195",
            "loan_fee_schedule_4194",
            "loan_fee_id_4194",
            "loan_fee_schedule_4735",
            "loan_fee_id_4735",
            "loan_override_sys_gen_penalty",
            "loan_manual_penalty_amount",
            "loan_status_id",
            "loan_title",
            "loan_description",
            "loan_fee_schedule_7548", 
            "loan_fee_id_7548",
            "loan_fee_schedule_7549", 
            "loan_fee_id_7549", 
            "loan_fee_schedule_7838", 
            "loan_fee_id_7838", 
            "loan_fee_schedule_7839", 
            "loan_fee_id_7839", 
            "loan_fee_schedule_7840", 
            "loan_fee_id_7840", 
            "borrower_id",
            "borrower_country",  
            "borrower_fullname", 
            "borrower_firstname",  
            "borrower_lastname",  
            "borrower_business_name",  
            "borrower_unique_number" , 
            "borrower_gender",  
            "borrower_title", 
            "borrower_mobile",  
            "borrower_email", 
            "borrower_dob",
            "borrower_address",  
            "borrower_city", 
            "borrower_province" ,
            "borrower_zipcode", 
            "borrower_landline",  
            "borrower_working_status", 
            "borrower_credit_score", 
            "borrower_description", 
            "borrower_access_ids",  
            "borrower_photo",
           # "createdby",
           ## "createdat",
            #"modifiedby",
            #"modifiedat"
        )

    
